- name: install packages needed for Kivy
  become: True
  apt:
    name: ['python3-pygame', 'python3-dev', 'libmtdev1', 'libgles2-mesa-dev']
    cache_valid_time: "{{ cache_update_valid_secs }}"


# leaving cython and kivy installs as separate tasks because
#   they take a long time - leaving them broken out increases visibility
#   and profiling of Ansible
- name: install cython
  become: True
  pip:
    name: cython==0.28.2

- name: check if required version of Kivy installed (saves times)
  stat:
    path: /usr/local/lib/python3.7/dist-packages/Kivy-1.10.1.dist-info/WHEEL
  register: kivy_package_installed

- name: install kivy
  become: True
  pip:
    name: git+https://github.com/kivy/kivy.git@ec0a82e
  when: kivy_package_installed.stat.exists == false

- name: generate kivy config for pi user
  command: python3 -c "from kivy.app import App;App().load_config()" creates={{ pi_user_kivy_config }}

- name: update pi user kivy config [input] for PiTFT 2.8" Capacitive
  ini_file:
    dest: "{{ pi_user_kivy_config }}"
    section: input
    option: "{{ item.key }}"
    value: "{{ item.value }}"
  with_dict: "{{ kivy_config_dict_input }}"
